services:
  api:
    container_name: evolution
    image: atendai/evolution-api:latest
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    networks:
      - evolution-net
    command: ["node", "./dist/src/main.js"]
    expose:
      - 8080
  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/certs-data:/data/letsencrypt
    networks:
      - evolution-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/certs-data:/data/letsencrypt
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'
    networks:
      - evolution-net

volumes:
  evolution_instances:
  evolution_store:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
