version: "3.3"

services:
  api:
    container_name: evolution
    image: atendai/evolution-api:latest
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    networks:
      - evolution-net
    command: ["node", "./dist/src/main.js"]
    expose:
      - 8080
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80

    depends_on:
      - api
volumes:
  evolution_instances:
  evolution_store:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
